from cvr_analysis.modalities_study.workflows.cvr_wf import cvr_wf
from cvr_analysis.modalities_study.workflows.post_processing import data_loader_wf, signal_processing_wf
from cvr_analysis.modalities_study.workflows.regression import setup_regression_wf, iterative_regression_wf

data_loader_wf.cacheNodesData(True)
signal_processing_wf.cacheNodesData(True)
setup_regression_wf.cacheNodesData(True)
iterative_regression_wf.cacheNodesData(True)