name: cvr
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pandas
  - numpy
  - nilearn
  - pybids
  - multiprocess
  - tqdm
  - scikit-learn
  - matplotlib
  - statsmodels
  - pip:
    - git+https://github.com/el-hult/pyppca